#image: ubuntu:artful
image: debian:testing-slim

stages:
  - test

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apt-get update
  - sh ci/install_basics.sh
  - pip install --process-dependency-links -r ci/requirements.txt
  - pip3 install --process-dependency-links -r ci/requirements.txt

test_min:
  stage: test
  script:
    - python setup.py install --user -f
    - python3 setup.py install --user -f
    - nosetests
    - mpiexec --allow-run-as-root -n 4 nosetests -x
    - mpiexec --allow-run-as-root -n 4 nosetests3 -x
    - nosetests3 -x --with-coverage --cover-package=nifty2go --cover-branches
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'
