image: docker:stable

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/ift/nifty:$CI_BUILD_REF_NAME

stages:
  - build_docker
  - test
  - release

build_docker:
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_python2_scalar:
  image: $CONTAINER_TEST_IMAGE
  stage: test
  script:
    - python setup.py install --user -f
    - nosetests -q --with-coverage --cover-package=nifty4 --cover-branches --cover-erase
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'

test_python3_scalar:
  image: $CONTAINER_TEST_IMAGE
  stage: test
  script:
    - python3 setup.py install --user -f
    - nosetests3 -q

test_python2_mpi:
  image: $CONTAINER_TEST_IMAGE
  stage: test
  script:
    - python setup.py install --user -f
    - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests -q 2> /dev/null

test_python3_mpi:
  image: $CONTAINER_TEST_IMAGE
  stage: test
  script:
    - python3 setup.py install --user -f
    - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests3 -q 2> /dev/null

pages:
  image: $CONTAINER_TEST_IMAGE
  stage: release
  script:
    - python setup.py install --user -f
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - NIFTy_4
