image: docker:stable

stages:
  - build_docker
  - test
  # - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/ift/nifty:$CI_BUILD_REF_NAME

# test_python2_scalar:
#   stage: test
#   script:
#     - python setup.py install --user -f
#     - nosetests -q --with-coverage --cover-package=nifty4 --cover-branches --cover-erase
#     - >
#       coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'

test_python3_scalar:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE python3 setup.py install --user -f
    - docker run $CONTAINER_TEST_IMAGE nosetests3 -q

# test_python2_mpi:
#   stage: test
#   script:
#     - python setup.py install --user -f
#     - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests -q 2> /dev/null

# test_python3_mpi:
#   stage: test
#   script:
#     - python3 setup.py install --user -f
#     - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests3 -q 2> /dev/null

# pages:
#   stage: release
#   script:
#     - python setup.py install --user -f
#     - sh docs/generate.sh
#     - mv docs/build/ public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - NIFTy_4

services:
  - docker:dind

build_docker_container:
  stage: build_docker
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
