#image: ubuntu:artful
image: debian:testing-slim

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apt-get update
  - sh ci/install_basics.sh
  - pip install --process-dependency-links -r ci/requirements.txt
  - pip3 install --process-dependency-links -r ci/requirements.txt

pages:
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install numpydoc
  - sphinx-apidoc -l -e -d 3 -o docs/source/mod nifty4
  - sphinx-build -b html docs/source/ docs/build/
  artifacts:
    paths:
    - ./docs/build
  only:
  - experiment_sphinx_gitlabpages




