image: ubuntu:latest

stages:
  - test

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apt-get update
  - chmod +x ci/*.sh
  - ci/install_basics.sh
  - pip install --upgrade -r ci/requirements.txt
  - pip3 install --upgrade -r ci/requirements.txt


test_min:
  stage: test
  script:
    - ci/install_pyHealpix.sh
    - ci/install_pyfftw.sh
    - nosetests
    - nosetests3
    - nosetests -x --with-coverage --cover-package=nifty --cover-branches
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'
