#image: ubuntu:artful
image: debian:testing-slim

stages:
  - test

variables:
  DOCKER_DRIVER: overlay

before_script:
  - apt-get update
  - sh ci/install_basics.sh
  - pip install --process-dependency-links -r ci/requirements.txt
  - pip3 install --process-dependency-links -r ci/requirements.txt

test_min:
  stage: test
  script:
    - pip install --user .
    - nosetests -q --with-coverage --cover-package=nifty4 --cover-branches
    - OMP_NUM_THREADS=1 mpiexec --allow-run-as-root -n 4 nosetests -q --with-coverage --cover-package=nifty4 --cover-branches
    - pip3 install --user .
    - nosetests3 -q
    - OMP_NUM_THREADS=1 mpiexec --allow-run-as-root -n 4 nosetests3 -q
    - coverage report
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }' || true
