image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  OMP_NUM_THREADS: 1

stages:
  - build_docker
  - test
  - release
  - demo_runs

build_docker_from_scratch:
  only:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE --no-cache .
    - docker push $CONTAINER_TEST_IMAGE

build_docker_from_cache:
  except:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_serial:
  stage: test
  script:
    - pytest-3 -q --cov=nifty7 test
    - >
      python3 -m coverage report --omit "*plot*" | tee coverage.txt
    - >
      grep TOTAL coverage.txt | awk '{ print "TOTAL: "$4; }'

test_mpi:
  stage: test
  variables:
    OMPI_MCA_btl_vader_single_copy_mechanism: none
  script:
    - mpiexec -n 2 --bind-to none pytest-3 -q test/test_mpi

pages:
  stage: release
  script:
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - NIFTy_6


before_script:
  - python3 setup.py install --user -f

run_ipynb0:
  stage: demo_runs
  script:
    - jupyter nbconvert --execute --ExecutePreprocessor.timeout=None demos/getting_started_0.ipynb

run_ipynb1:
  stage: demo_runs
  script:
    - jupyter nbconvert --execute --ExecutePreprocessor.timeout=None demos/getting_started_4_CorrelatedFields.ipynb

run_getting_started_1:
  stage: demo_runs
  script:
    - python3 demos/getting_started_1.py
    - mpiexec -n 2 --bind-to none python3 demos/getting_started_1.py 2> /dev/null
  artifacts:
    paths:
      - '*.png'

run_getting_started_2:
  stage: demo_runs
  script:
    - python3 demos/getting_started_2.py
    - mpiexec -n 2 --bind-to none python3 demos/getting_started_2.py 2> /dev/null
  artifacts:
    paths:
      - '*.png'

run_getting_started_3:
  stage: demo_runs
  script:
    - python3 demos/getting_started_3.py
  artifacts:
    paths:
      - '*.png'

run_getting_started_mf:
  stage: demo_runs
  script:
    - python3 demos/getting_started_5_mf.py
  artifacts:
    paths:
      - '*.png'

run_bernoulli:
  stage: demo_runs
  script:
    - python3 demos/bernoulli_demo.py
  artifacts:
    paths:
      - '*.png'

run_curve_fitting:
  stage: demo_runs
  script:
    - python3 demos/polynomial_fit.py
  artifacts:
    paths:
      - '*.png'

run_visual_mgvi:
  stage: demo_runs
  script:
    - python3 demos/mgvi_visualized.py
