image: parras/nifty:latest

stages:
  - test
  - release

variables:
  DOCKER_DRIVER: overlay

test_scalar:
  stage: test
  script:
    - python setup.py install --user -f
    - python3 setup.py install --user -f
    - nosetests3 -q
    - nosetests -q --with-coverage --cover-package=nifty4 --cover-branches --cover-erase
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'

test_mpi:
  stage: test
  script:
    - python setup.py install --user -f
    - python3 setup.py install --user -f
    - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests -q
    - OMP_NUM_THREADS=1 mpiexec -n 2 nosetests3 -q

pages:
  stage: release
  script:
    - python setup.py install --user -f
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - NIFTy_4
