image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/ift/nifty:$CI_BUILD_REF_NAME
  OMP_NUM_THREADS: 1

stages:
  - build_docker
  - test
  - release

build_docker_from_scratch:
  only:
    - schedules
  image: docker:stable
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE --no-cache .
    - docker push $CONTAINER_TEST_IMAGE

build_docker_from_cache:
  except:
    - schedules
  image: docker:stable
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_python2_scalar:
  stage: test
  script:
    - python setup.py install --user -f
    - nosetests -q

test_python3_scalar:
  stage: test
  script:
    - python3 setup.py install --user -f
    - nosetests3 -q

test_python2_mpi:
  stage: test
  script:
    - python setup.py install --user -f
    - mpiexec -n 2 --bind-to none nosetests -q 2> /dev/null

test_python3_mpi:
  stage: test
  script:
    - python3 setup.py install --user -f
    - mpiexec -n 2 --bind-to none nosetests3 -q 2> /dev/null

test_coverage:
  stage: test
  script:
    - python setup.py install --user -f
    - mpiexec -n 2 --bind-to none nosetests -q --with-coverage --cover-package=nifty4 --cover-branches --cover-erase 2> /dev/null
    - nosetests -q --with-coverage --cover-package=nifty4 --cover-branches --cover-erase
    - >
      coverage report | grep TOTAL | awk '{ print "TOTAL: "$6; }'

pages:
  stage: release
  script:
    - python setup.py install --user -f
    - sh docs/generate.sh
    - mv docs/build/ public/
  artifacts:
    paths:
    - public
  only:
  - NIFTy_4
